version: "3.8"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  memecoin-api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
